"""unicite participant par equipe

Revision ID: 4667bbc184b6
Revises: 55a85c0485fd
Create Date: 2026-10-05 19:54:50.610453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4667bbc184b6'
down_revision: Union[str, Sequence[str], None] = '55a85c0485fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_participants_equipe_utilisateur', 'participants', ['equipe_id', 'id_utilisateur'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participants_equipe_utilisateur', 'participants', type_='unique')
    # ### end Alembic commands ###
