"""creation initiale + module missions

Revision ID: b56d59a3f80e
Revises: 
Create Date: 2026-10-04 18:15:37.544426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56d59a3f80e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('electrifie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('type_mission', sa.String(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin_prevue', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politiques_conformite',
    sa.Column('id_politique', sa.Integer(), nullable=False),
    sa.Column('nom_politique', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('seuils_configures', sa.String(length=255), nullable=False),
    sa.Column('date_effective', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_politique')
    )
    op.create_table('roles_permissions',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('nom_role', sa.String(length=50), nullable=False),
    sa.Column('niveau_acces', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('nom_role')
    )
    op.create_table('services_communes',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('nom_service', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('id_service_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_service_parent'], ['services_communes.id_service'], ),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.create_table('axes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('numero_axe', sa.Integer(), nullable=True),
    sa.Column('itineraire_principal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmarking_services',
    sa.Column('id_benchmark', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('score_risque_moyen', sa.Float(), nullable=False),
    sa.Column('rang', sa.Integer(), nullable=True),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['services_communes.id_service'], ),
    sa.PrimaryKeyConstraint('id_benchmark')
    )
    op.create_table('rapports_audit',
    sa.Column('id_rapport', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.Column('periode_couverte', sa.String(length=20), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_generation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['services_communes.id_service'], ),
    sa.PrimaryKeyConstraint('id_rapport')
    )
    op.create_table('ressources_sensibles',
    sa.Column('id_ressource', sa.Integer(), nullable=False),
    sa.Column('type_ressource', sa.String(length=100), nullable=False),
    sa.Column('niveau_sensibilite', sa.String(length=20), nullable=False),
    sa.Column('id_service_proprietaire', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_service_proprietaire'], ['services_communes.id_service'], ),
    sa.PrimaryKeyConstraint('id_ressource')
    )
    op.create_table('utilisateurs',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('matricule', sa.String(length=30), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles_permissions.id_role'], ),
    sa.ForeignKeyConstraint(['id_service'], ['services_communes.id_service'], ),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('matricule')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axe_id', sa.Integer(), nullable=False),
    sa.Column('type_equipe', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['axe_id'], ['axes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_acces',
    sa.Column('id_entree', sa.BigInteger(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_ressource', sa.Integer(), nullable=False),
    sa.Column('type_action', sa.String(length=30), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('adresse_ip', sa.String(length=45), nullable=False),
    sa.Column('hash_entree', sa.String(length=64), nullable=False),
    sa.Column('hash_precedent', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['id_ressource'], ['ressources_sensibles.id_ressource'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_entree'),
    sa.UniqueConstraint('hash_entree')
    )
    op.create_table('missions_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axe_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('ordre_visite', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['axe_id'], ['axes.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profils_comportementaux',
    sa.Column('id_profil', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('periode_reference', sa.String(length=20), nullable=False),
    sa.Column('volume_moyen', sa.Float(), nullable=False),
    sa.Column('horaires_habituels', sa.String(length=50), nullable=False),
    sa.Column('perimetre_habituel', sa.String(length=255), nullable=False),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_profil')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('fonction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores_anomalie',
    sa.Column('id_score', sa.BigInteger(), nullable=False),
    sa.Column('id_entree_journal', sa.BigInteger(), nullable=False),
    sa.Column('id_profil_reference', sa.Integer(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('methode_utilisee', sa.String(length=50), nullable=False),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_entree_journal'], ['journal_acces.id_entree'], ),
    sa.ForeignKeyConstraint(['id_profil_reference'], ['profils_comportementaux.id_profil'], ),
    sa.PrimaryKeyConstraint('id_score')
    )
    op.create_table('alertes_securite',
    sa.Column('id_alerte', sa.Integer(), nullable=False),
    sa.Column('id_score', sa.BigInteger(), nullable=False),
    sa.Column('id_politique', sa.Integer(), nullable=False),
    sa.Column('niveau_gravite', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_politique'], ['politiques_conformite.id_politique'], ),
    sa.ForeignKeyConstraint(['id_score'], ['scores_anomalie.id_score'], ),
    sa.PrimaryKeyConstraint('id_alerte')
    )
    op.create_table('investigations',
    sa.Column('id_investigation', sa.Integer(), nullable=False),
    sa.Column('id_alerte', sa.Integer(), nullable=False),
    sa.Column('id_enqueteur', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('conclusion', sa.String(length=500), nullable=True),
    sa.Column('date_ouverture', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_cloture', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_alerte'], ['alertes_securite.id_alerte'], ),
    sa.ForeignKeyConstraint(['id_enqueteur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_investigation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigations')
    op.drop_table('alertes_securite')
    op.drop_table('scores_anomalie')
    op.drop_table('participants')
    op.drop_table('profils_comportementaux')
    op.drop_table('missions_districts')
    op.drop_table('journal_acces')
    op.drop_table('equipes')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('ressources_sensibles')
    op.drop_table('rapports_audit')
    op.drop_table('benchmarking_services')
    op.drop_table('axes')
    op.drop_table('services_communes')
    op.drop_table('roles_permissions')
    op.drop_table('politiques_conformite')
    op.drop_table('missions')
    op.drop_table('districts')
    # ### end Alembic commands ###
