"""ajout phases, journees, livrables, indicateurs, types_activite

Revision ID: e939075e7644
Revises: b56d59a3f80e
Create Date: 2026-10-04 20:09:36.779565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e939075e7644'
down_revision: Union[str, Sequence[str], None] = 'b56d59a3f80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicateurs_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('resultat_attendu', sa.String(), nullable=True),
    sa.Column('indicateur_mesure', sa.String(), nullable=True),
    sa.Column('cible', sa.String(), nullable=True),
    sa.Column('valeur_realisee', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_district_id', sa.Integer(), nullable=False),
    sa.Column('numero_jour', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('lieu', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mission_district_id'], ['missions_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_district_id', sa.Integer(), nullable=False),
    sa.Column('type_activite_id', sa.Integer(), nullable=False),
    sa.Column('numero_ordre', sa.Integer(), nullable=True),
    sa.Column('duree_prevue', sa.String(), nullable=True),
    sa.Column('livrable_attendu', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mission_district_id'], ['missions_districts.id'], ),
    sa.ForeignKeyConstraint(['type_activite_id'], ['types_activite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livrables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('type_livrable', sa.String(), nullable=True),
    sa.Column('date_production', sa.DateTime(), nullable=True),
    sa.Column('signe', sa.Boolean(), nullable=True),
    sa.Column('fichier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livrables')
    op.drop_table('phases')
    op.drop_table('journees')
    op.drop_table('indicateurs_performance')
    op.drop_table('types_activite')
    # ### end Alembic commands ###
